#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


name: IT

on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches: [ master, dev ]
  #     paths:
  #       - '.github/workflows/it.yml'
  #       - '**/pom.xml'
  #       - '**/src/main/**'
  #       - 'distribution/proxy/**'
  #       - 'test/pom.xml'
  #       - 'test/integration-test/fixture/**'
  #       - 'test/integration-test/env/**'
  #       - 'test/integration-test/test-suite/**'
  #       - 'test/integration-agent-test/**'
  #       - '!examples/**'
  #       - '!distribution/**'
  #       - '!distribution/proxy/src/main/release-docs/**'
  #       - '!kernel/data-pipeline/**'
  #       - '!test/**'
  #       - '!*.md'
  pull_request:
    branches: [ master ]
#     paths:
#       - '.github/workflows/it.yml'
#       - '**/pom.xml'
#       - '**/src/main/**'
#       - 'distribution/proxy/**'
#       - '!test/**'
#       - 'test/pom.xml'
#       - 'test/integration-test/fixture/**'
#       - 'test/integration-test/env/**'
#       - 'test/integration-test/test-suite/**'
#       - 'test/integration-agent-test/**'
#       - '!examples/**'
#       - '!distribution/**'
#       - '!distribution/proxy/src/main/release-docs/**'
#       - '!kernel/data-pipeline/**'
#       - '!*.md'


jobs:
#  #v8
#  java-v8-temurin:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-temurin.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  java-v8-zulu:
#    needs: java-v8-temurin
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-zulu.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  java-v8-adopt:
#    needs: java-v8-zulu
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-adopt.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  java-v8-adopt-openj9:
#    needs: java-v8-adopt
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-adopt-openj9.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v8-liberica:
#    needs: java-v8-adopt-openj9
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-liberica.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
##  java-v8-microsoft:
##    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-microsoft.yml@dev
##    secrets:
##      it_password: ${{secrets.it_password}}
#
#  java-v8-corretto:
#    needs: java-v8-liberica
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v8-corretto.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  #v11
#  java-v11-temurin:
##    needs: java-v8-corretto
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-temurin.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  java-v11-zulu:
#    needs: java-v11-temurin
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-zulu.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v11-adopt:
#    needs: java-v11-zulu
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-adopt.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v11-adopt-openj9:
#    needs: java-v11-adopt
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-adopt-openj9.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}

  java-v11-liberica:
#    needs: java-v11-adopt-openj9
    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-liberica.yml@dev
    secrets:
      it_password: ${{secrets.it_password}}

  java-v11-microsoft:
    needs: java-v11-liberica
    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-microsoft.yml@dev
    secrets:
      it_password: ${{secrets.it_password}}

  java-v11-corretto:
    needs: java-v11-microsoft
    uses: Patrick1S/shardingsphere/.github/workflows/java-v11-corretto.yml@dev
    secrets:
      it_password: ${{secrets.it_password}}

  #v17
  java-v17-temurin:
    needs: java-v11-corretto
    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-temurin.yml@dev
    secrets:
      it_password: ${{secrets.it_password}}


  java-v17-zulu:
    needs: java-v17-temurin
    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-zulu.yml@dev
    secrets:
      it_password: ${{secrets.it_password}}
#
#  java-v17-adopt:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-adopt.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v17-adopt-openj9:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-adopt-openj9.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v17-liberica:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-liberica.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v17-microsoft:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-microsoft.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v17-corretto:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v17-corretto.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#
#  #v19
#  java-v19-temurin:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-temurin.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#  java-v19-zulu:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-zulu.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#  java-v19-adopt:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-adopt.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
##  java-v19-adopt-openj9:
##    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-adopt-openj9.yml@dev
##    secrets:
##      it_password: ${{secrets.it_password}}
#
#  java-v19-liberica:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-liberica.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
##  java-v19-microsoft:
##    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-microsoft.yml@dev
##    secrets:
##      it_password: ${{secrets.it_password}}
#
#  java-v19-corretto:
#    uses: Patrick1S/shardingsphere/.github/workflows/java-v19-corretto.yml@dev
#    secrets:
#      it_password: ${{secrets.it_password}}
#
#
#
